# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/users/ankha/desktop/fpga_design/khanhtran_lab4/vivado_codes_lab4/tmp_edit_project.srcs/sources_1/bd/Vivado_IP_Design/ip/Vivado_IP_Design_rst_clk_wiz_0_100M_0/Vivado_IP_Design_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'Vivado_IP_Design_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/users/ankha/desktop/fpga_design/khanhtran_lab4/vivado_codes_lab4/tmp_edit_project.gen/sources_1/bd/Vivado_IP_Design/ip/Vivado_IP_Design_rst_clk_wiz_0_100M_0/Vivado_IP_Design_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vivado_IP_Design_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/users/ankha/desktop/fpga_design/khanhtran_lab4/vivado_codes_lab4/tmp_edit_project.gen/sources_1/bd/Vivado_IP_Design/ip/Vivado_IP_Design_rst_clk_wiz_0_100M_0/Vivado_IP_Design_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vivado_IP_Design_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/users/ankha/desktop/fpga_design/khanhtran_lab4/vivado_codes_lab4/tmp_edit_project.srcs/sources_1/bd/Vivado_IP_Design/ip/Vivado_IP_Design_rst_clk_wiz_0_100M_0/Vivado_IP_Design_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'Vivado_IP_Design_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/users/ankha/desktop/fpga_design/khanhtran_lab4/vivado_codes_lab4/tmp_edit_project.gen/sources_1/bd/Vivado_IP_Design/ip/Vivado_IP_Design_rst_clk_wiz_0_100M_0/Vivado_IP_Design_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vivado_IP_Design_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/users/ankha/desktop/fpga_design/khanhtran_lab4/vivado_codes_lab4/tmp_edit_project.gen/sources_1/bd/Vivado_IP_Design/ip/Vivado_IP_Design_rst_clk_wiz_0_100M_0/Vivado_IP_Design_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vivado_IP_Design_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
