// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mux_2to1_mux_2to1,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.993000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=2,HLS_VERSION=2025_1}" *)

module mux_2to1 (
        a,
        b,
        sel,
        y,
        ap_rst
);


input  [0:0] a;
input  [0:0] b;
input  [0:0] sel;
output  [0:0] y;
input   ap_rst;

assign y = ((sel[0:0] == 1'b1) ? b : a);

endmodule //mux_2to1
