// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="maxmul2x2_maxmul2x2,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.930000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=439,HLS_SYN_LUT=622,HLS_VERSION=2025_1}" *)

module maxmul2x2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a00,
        a01,
        a10,
        a11,
        b00,
        b01,
        b10,
        b11,
        c00,
        c01,
        c10,
        c11
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] a00;
input  [15:0] a01;
input  [15:0] a10;
input  [15:0] a11;
input  [15:0] b00;
input  [15:0] b01;
input  [15:0] b10;
input  [15:0] b11;
output  [31:0] c00;
output  [31:0] c01;
output  [31:0] c10;
output  [31:0] c11;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln14_fu_300_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] b11_read_reg_510;
reg   [15:0] b10_read_reg_515;
reg   [15:0] a11_read_reg_520;
reg   [15:0] a01_read_reg_525;
wire   [1:0] select_ln14_fu_218_p3;
reg   [1:0] select_ln14_reg_530;
reg   [1:0] select_ln14_reg_530_pp0_iter1_reg;
reg   [1:0] select_ln14_reg_530_pp0_iter2_reg;
wire   [0:0] icmp_ln20_fu_234_p2;
reg   [0:0] icmp_ln20_reg_535;
wire   [0:0] cond_fu_252_p2;
reg   [0:0] cond_reg_545;
reg   [0:0] cond_reg_545_pp0_iter1_reg;
reg   [0:0] cond_reg_545_pp0_iter2_reg;
wire   [0:0] icmp_ln20_1_fu_258_p2;
reg   [0:0] icmp_ln20_1_reg_553;
wire   [0:0] icmp_ln16_fu_288_p2;
reg   [0:0] icmp_ln16_reg_563;
reg   [0:0] icmp_ln14_reg_568;
reg   [0:0] icmp_ln14_reg_568_pp0_iter1_reg;
reg   [0:0] icmp_ln14_reg_568_pp0_iter2_reg;
wire   [31:0] mul_ln20_fu_344_p2;
reg  signed [31:0] mul_ln20_reg_572;
reg   [0:0] ap_phi_mux_icmp_ln1612_phi_fu_179_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [1:0] indvar_flatten9_fu_68;
wire   [1:0] add_ln14_1_fu_282_p2;
reg   [1:0] ap_sig_allocacmp_indvar_flatten9_load;
reg   [1:0] i10_fu_72;
wire   [1:0] i_fu_226_p3;
reg   [1:0] ap_sig_allocacmp_i10_load;
reg   [31:0] empty_fu_76;
wire   [31:0] empty_8_fu_395_p3;
reg   [31:0] empty_5_fu_80;
wire   [31:0] empty_9_fu_403_p3;
reg   [31:0] empty_6_fu_84;
wire   [31:0] empty_10_fu_411_p3;
reg   [31:0] empty_7_fu_88;
wire   [31:0] empty_11_fu_419_p3;
reg   [1:0] j11_fu_92;
wire   [1:0] j_fu_276_p2;
reg   [1:0] ap_sig_allocacmp_j11_load;
reg   [1:0] add_ln1413_fu_96;
wire   [1:0] add_ln14_fu_294_p2;
reg   [1:0] ap_sig_allocacmp_add_ln1413_load;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
wire    ap_block_pp0_stage0_01001;
wire  signed [15:0] select_ln20_fu_240_p3;
wire  signed [15:0] select_ln20_2_fu_264_p3;
wire  signed [15:0] select_ln20_1_fu_326_p3;
wire  signed [15:0] select_ln20_3_fu_335_p3;
wire   [0:0] first_iter_0_fu_362_p2;
wire  signed [31:0] grp_fu_447_p3;
wire   [31:0] select_ln22_2_fu_381_p3;
wire   [31:0] select_ln22_3_fu_388_p3;
wire   [31:0] select_ln22_fu_367_p3;
wire   [31:0] select_ln22_1_fu_374_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_112;
reg    ap_condition_346;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 indvar_flatten9_fu_68 = 2'd0;
#0 i10_fu_72 = 2'd0;
#0 empty_fu_76 = 32'd0;
#0 empty_5_fu_80 = 32'd0;
#0 empty_6_fu_84 = 32'd0;
#0 empty_7_fu_88 = 32'd0;
#0 j11_fu_92 = 2'd0;
#0 add_ln1413_fu_96 = 2'd0;
#0 ap_done_reg = 1'b0;
end

maxmul2x2_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U1(
    .din0(select_ln20_3_fu_335_p3),
    .din1(select_ln20_1_fu_326_p3),
    .dout(mul_ln20_fu_344_p2)
);

maxmul2x2_mac_muladd_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln20_2_fu_264_p3),
    .din1(select_ln20_fu_240_p3),
    .din2(mul_ln20_reg_572),
    .ce(1'b1),
    .dout(grp_fu_447_p3)
);

maxmul2x2_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_112)) begin
        add_ln1413_fu_96 <= add_ln14_fu_294_p2;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0))) begin
    ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_112)) begin
    i10_fu_72 <= i_fu_226_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_112)) begin
    indvar_flatten9_fu_68 <= add_ln14_1_fu_282_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_112)) begin
    j11_fu_92 <= j_fu_276_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a01_read_reg_525 <= a01;
        a11_read_reg_520 <= a11;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        b10_read_reg_515 <= b10;
        b11_read_reg_510 <= b11;
        cond_reg_545 <= cond_fu_252_p2;
        cond_reg_545_pp0_iter1_reg <= cond_reg_545;
        icmp_ln14_reg_568 <= icmp_ln14_fu_300_p2;
        icmp_ln14_reg_568_pp0_iter1_reg <= icmp_ln14_reg_568;
        icmp_ln20_1_reg_553 <= icmp_ln20_1_fu_258_p2;
        icmp_ln20_reg_535 <= icmp_ln20_fu_234_p2;
        mul_ln20_reg_572 <= mul_ln20_fu_344_p2;
        select_ln14_reg_530 <= select_ln14_fu_218_p3;
        select_ln14_reg_530_pp0_iter1_reg <= select_ln14_reg_530;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        cond_reg_545_pp0_iter2_reg <= cond_reg_545_pp0_iter1_reg;
        icmp_ln14_reg_568_pp0_iter2_reg <= icmp_ln14_reg_568_pp0_iter1_reg;
        select_ln14_reg_530_pp0_iter2_reg <= select_ln14_reg_530_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        empty_5_fu_80 <= empty_9_fu_403_p3;
        empty_6_fu_84 <= empty_10_fu_411_p3;
        empty_7_fu_88 <= empty_11_fu_419_p3;
        empty_fu_76 <= empty_8_fu_395_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln16_reg_563 <= icmp_ln16_fu_288_p2;
    end
end

always @ (*) begin
    if (((icmp_ln14_fu_300_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_346)) begin
            ap_phi_mux_icmp_ln1612_phi_fu_179_p4 = icmp_ln16_reg_563;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln1612_phi_fu_179_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln1612_phi_fu_179_p4 = icmp_ln16_reg_563;
        end
    end else begin
        ap_phi_mux_icmp_ln1612_phi_fu_179_p4 = icmp_ln16_reg_563;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_add_ln1413_load = 2'd1;
    end else begin
        ap_sig_allocacmp_add_ln1413_load = add_ln1413_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i10_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i10_load = i10_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten9_load = 2'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten9_load = indvar_flatten9_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j11_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j11_load = j11_fu_92;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln14_1_fu_282_p2 = (ap_sig_allocacmp_indvar_flatten9_load + 2'd1);

assign add_ln14_fu_294_p2 = (i_fu_226_p3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_112 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_346 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln14_reg_568 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign c00 = ((cond_reg_545_pp0_iter2_reg[0:0] == 1'b1) ? select_ln22_1_fu_374_p3 : empty_7_fu_88);

assign c01 = ((cond_reg_545_pp0_iter2_reg[0:0] == 1'b1) ? select_ln22_fu_367_p3 : empty_6_fu_84);

assign c10 = ((cond_reg_545_pp0_iter2_reg[0:0] == 1'b1) ? empty_5_fu_80 : select_ln22_3_fu_388_p3);

assign c11 = ((cond_reg_545_pp0_iter2_reg[0:0] == 1'b1) ? empty_fu_76 : select_ln22_2_fu_381_p3);

assign cond_fu_252_p2 = ((i_fu_226_p3 == 2'd0) ? 1'b1 : 1'b0);

assign empty_10_fu_411_p3 = ((cond_reg_545_pp0_iter2_reg[0:0] == 1'b1) ? select_ln22_fu_367_p3 : empty_6_fu_84);

assign empty_11_fu_419_p3 = ((cond_reg_545_pp0_iter2_reg[0:0] == 1'b1) ? select_ln22_1_fu_374_p3 : empty_7_fu_88);

assign empty_8_fu_395_p3 = ((cond_reg_545_pp0_iter2_reg[0:0] == 1'b1) ? empty_fu_76 : select_ln22_2_fu_381_p3);

assign empty_9_fu_403_p3 = ((cond_reg_545_pp0_iter2_reg[0:0] == 1'b1) ? empty_5_fu_80 : select_ln22_3_fu_388_p3);

assign first_iter_0_fu_362_p2 = ((select_ln14_reg_530_pp0_iter2_reg == 2'd0) ? 1'b1 : 1'b0);

assign i_fu_226_p3 = ((ap_phi_mux_icmp_ln1612_phi_fu_179_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln1413_load : ap_sig_allocacmp_i10_load);

assign icmp_ln14_fu_300_p2 = ((ap_sig_allocacmp_indvar_flatten9_load == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_288_p2 = ((j_fu_276_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln20_1_fu_258_p2 = ((select_ln14_fu_218_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_234_p2 = ((i_fu_226_p3 == 2'd1) ? 1'b1 : 1'b0);

assign j_fu_276_p2 = (select_ln14_fu_218_p3 + 2'd1);

assign select_ln14_fu_218_p3 = ((ap_phi_mux_icmp_ln1612_phi_fu_179_p4[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j11_load);

assign select_ln20_1_fu_326_p3 = ((icmp_ln20_reg_535[0:0] == 1'b1) ? a11_read_reg_520 : a01_read_reg_525);

assign select_ln20_2_fu_264_p3 = ((icmp_ln20_1_fu_258_p2[0:0] == 1'b1) ? b01 : b00);

assign select_ln20_3_fu_335_p3 = ((icmp_ln20_1_reg_553[0:0] == 1'b1) ? b11_read_reg_510 : b10_read_reg_515);

assign select_ln20_fu_240_p3 = ((icmp_ln20_fu_234_p2[0:0] == 1'b1) ? a10 : a00);

assign select_ln22_1_fu_374_p3 = ((first_iter_0_fu_362_p2[0:0] == 1'b1) ? grp_fu_447_p3 : empty_7_fu_88);

assign select_ln22_2_fu_381_p3 = ((first_iter_0_fu_362_p2[0:0] == 1'b1) ? empty_fu_76 : grp_fu_447_p3);

assign select_ln22_3_fu_388_p3 = ((first_iter_0_fu_362_p2[0:0] == 1'b1) ? grp_fu_447_p3 : empty_5_fu_80);

assign select_ln22_fu_367_p3 = ((first_iter_0_fu_362_p2[0:0] == 1'b1) ? empty_6_fu_84 : grp_fu_447_p3);

endmodule //maxmul2x2
