-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity maxmul2x2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a00 : IN STD_LOGIC_VECTOR (15 downto 0);
    a01 : IN STD_LOGIC_VECTOR (15 downto 0);
    a10 : IN STD_LOGIC_VECTOR (15 downto 0);
    a11 : IN STD_LOGIC_VECTOR (15 downto 0);
    b00 : IN STD_LOGIC_VECTOR (15 downto 0);
    b01 : IN STD_LOGIC_VECTOR (15 downto 0);
    b10 : IN STD_LOGIC_VECTOR (15 downto 0);
    b11 : IN STD_LOGIC_VECTOR (15 downto 0);
    c00 : OUT STD_LOGIC_VECTOR (31 downto 0);
    c01 : OUT STD_LOGIC_VECTOR (31 downto 0);
    c10 : OUT STD_LOGIC_VECTOR (31 downto 0);
    c11 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of maxmul2x2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "maxmul2x2_maxmul2x2,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.930000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=439,HLS_SYN_LUT=622,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln14_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal b11_read_reg_510 : STD_LOGIC_VECTOR (15 downto 0);
    signal b10_read_reg_515 : STD_LOGIC_VECTOR (15 downto 0);
    signal a11_read_reg_520 : STD_LOGIC_VECTOR (15 downto 0);
    signal a01_read_reg_525 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln14_fu_218_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln14_reg_530 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln14_reg_530_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln14_reg_530_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln20_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_535 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_545 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_545_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_545_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_1_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_1_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_reg_563 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_reg_568 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_reg_568_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_reg_568_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln20_fu_344_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln20_reg_572 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_icmp_ln1612_phi_fu_179_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal indvar_flatten9_fu_68 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln14_1_fu_282_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_indvar_flatten9_load : STD_LOGIC_VECTOR (1 downto 0);
    signal i10_fu_72 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal i_fu_226_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i10_load : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_fu_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal empty_8_fu_395_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_5_fu_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal empty_9_fu_403_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_6_fu_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal empty_10_fu_411_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_7_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal empty_11_fu_419_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal j11_fu_92 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal j_fu_276_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_j11_load : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln1413_fu_96 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln14_fu_294_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_add_ln1413_load : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal select_ln20_fu_240_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln20_2_fu_264_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln20_1_fu_326_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln20_3_fu_335_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal first_iter_0_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_447_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_2_fu_381_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_3_fu_388_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_fu_367_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_1_fu_374_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_112 : BOOLEAN;
    signal ap_condition_346 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component maxmul2x2_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component maxmul2x2_mac_muladd_16s_16s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component maxmul2x2_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_16s_16s_32_1_1_U1 : component maxmul2x2_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => select_ln20_3_fu_335_p3,
        din1 => select_ln20_1_fu_326_p3,
        dout => mul_ln20_fu_344_p2);

    mac_muladd_16s_16s_32s_32_4_1_U2 : component maxmul2x2_mac_muladd_16s_16s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln20_2_fu_264_p3,
        din1 => select_ln20_fu_240_p3,
        din2 => mul_ln20_reg_572,
        ce => ap_const_logic_1,
        dout => grp_fu_447_p3);

    flow_control_loop_pipe_U : component maxmul2x2_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    add_ln1413_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_112)) then
                add_ln1413_fu_96 <= add_ln14_fu_294_p2;
            end if;
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    i10_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_112)) then
                i10_fu_72 <= i_fu_226_p3;
            end if;
        end if;
    end process;

    indvar_flatten9_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_112)) then
                indvar_flatten9_fu_68 <= add_ln14_1_fu_282_p2;
            end if;
        end if;
    end process;

    j11_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_112)) then
                j11_fu_92 <= j_fu_276_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a01_read_reg_525 <= a01;
                a11_read_reg_520 <= a11;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                b10_read_reg_515 <= b10;
                b11_read_reg_510 <= b11;
                cond_reg_545 <= cond_fu_252_p2;
                cond_reg_545_pp0_iter1_reg <= cond_reg_545;
                icmp_ln14_reg_568 <= icmp_ln14_fu_300_p2;
                icmp_ln14_reg_568_pp0_iter1_reg <= icmp_ln14_reg_568;
                icmp_ln20_1_reg_553 <= icmp_ln20_1_fu_258_p2;
                icmp_ln20_reg_535 <= icmp_ln20_fu_234_p2;
                mul_ln20_reg_572 <= mul_ln20_fu_344_p2;
                select_ln14_reg_530 <= select_ln14_fu_218_p3;
                select_ln14_reg_530_pp0_iter1_reg <= select_ln14_reg_530;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                cond_reg_545_pp0_iter2_reg <= cond_reg_545_pp0_iter1_reg;
                icmp_ln14_reg_568_pp0_iter2_reg <= icmp_ln14_reg_568_pp0_iter1_reg;
                select_ln14_reg_530_pp0_iter2_reg <= select_ln14_reg_530_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                empty_5_fu_80 <= empty_9_fu_403_p3;
                empty_6_fu_84 <= empty_10_fu_411_p3;
                empty_7_fu_88 <= empty_11_fu_419_p3;
                empty_fu_76 <= empty_8_fu_395_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln16_reg_563 <= icmp_ln16_fu_288_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln14_1_fu_282_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten9_load) + unsigned(ap_const_lv2_1));
    add_ln14_fu_294_p2 <= std_logic_vector(unsigned(i_fu_226_p3) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_112_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_112 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_346_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln14_reg_568, ap_block_pp0_stage0)
    begin
                ap_condition_346 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln14_reg_568 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln14_fu_300_p2)
    begin
        if (((icmp_ln14_fu_300_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_icmp_ln1612_phi_fu_179_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln16_reg_563, ap_loop_init, ap_condition_346)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_346)) then 
                ap_phi_mux_icmp_ln1612_phi_fu_179_p4 <= icmp_ln16_reg_563;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln1612_phi_fu_179_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln1612_phi_fu_179_p4 <= icmp_ln16_reg_563;
            end if;
        else 
            ap_phi_mux_icmp_ln1612_phi_fu_179_p4 <= icmp_ln16_reg_563;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_add_ln1413_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, add_ln1413_fu_96)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_add_ln1413_load <= ap_const_lv2_1;
        else 
            ap_sig_allocacmp_add_ln1413_load <= add_ln1413_fu_96;
        end if; 
    end process;


    ap_sig_allocacmp_i10_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, i10_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i10_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i10_load <= i10_fu_72;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten9_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten9_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten9_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_indvar_flatten9_load <= indvar_flatten9_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_j11_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, j11_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j11_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j11_load <= j11_fu_92;
        end if; 
    end process;

    c00 <= 
        select_ln22_1_fu_374_p3 when (cond_reg_545_pp0_iter2_reg(0) = '1') else 
        empty_7_fu_88;
    c01 <= 
        select_ln22_fu_367_p3 when (cond_reg_545_pp0_iter2_reg(0) = '1') else 
        empty_6_fu_84;
    c10 <= 
        empty_5_fu_80 when (cond_reg_545_pp0_iter2_reg(0) = '1') else 
        select_ln22_3_fu_388_p3;
    c11 <= 
        empty_fu_76 when (cond_reg_545_pp0_iter2_reg(0) = '1') else 
        select_ln22_2_fu_381_p3;
    cond_fu_252_p2 <= "1" when (i_fu_226_p3 = ap_const_lv2_0) else "0";
    empty_10_fu_411_p3 <= 
        select_ln22_fu_367_p3 when (cond_reg_545_pp0_iter2_reg(0) = '1') else 
        empty_6_fu_84;
    empty_11_fu_419_p3 <= 
        select_ln22_1_fu_374_p3 when (cond_reg_545_pp0_iter2_reg(0) = '1') else 
        empty_7_fu_88;
    empty_8_fu_395_p3 <= 
        empty_fu_76 when (cond_reg_545_pp0_iter2_reg(0) = '1') else 
        select_ln22_2_fu_381_p3;
    empty_9_fu_403_p3 <= 
        empty_5_fu_80 when (cond_reg_545_pp0_iter2_reg(0) = '1') else 
        select_ln22_3_fu_388_p3;
    first_iter_0_fu_362_p2 <= "1" when (select_ln14_reg_530_pp0_iter2_reg = ap_const_lv2_0) else "0";
    i_fu_226_p3 <= 
        ap_sig_allocacmp_add_ln1413_load when (ap_phi_mux_icmp_ln1612_phi_fu_179_p4(0) = '1') else 
        ap_sig_allocacmp_i10_load;
    icmp_ln14_fu_300_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten9_load = ap_const_lv2_3) else "0";
    icmp_ln16_fu_288_p2 <= "1" when (j_fu_276_p2 = ap_const_lv2_2) else "0";
    icmp_ln20_1_fu_258_p2 <= "1" when (select_ln14_fu_218_p3 = ap_const_lv2_1) else "0";
    icmp_ln20_fu_234_p2 <= "1" when (i_fu_226_p3 = ap_const_lv2_1) else "0";
    j_fu_276_p2 <= std_logic_vector(unsigned(select_ln14_fu_218_p3) + unsigned(ap_const_lv2_1));
    select_ln14_fu_218_p3 <= 
        ap_const_lv2_0 when (ap_phi_mux_icmp_ln1612_phi_fu_179_p4(0) = '1') else 
        ap_sig_allocacmp_j11_load;
    select_ln20_1_fu_326_p3 <= 
        a11_read_reg_520 when (icmp_ln20_reg_535(0) = '1') else 
        a01_read_reg_525;
    select_ln20_2_fu_264_p3 <= 
        b01 when (icmp_ln20_1_fu_258_p2(0) = '1') else 
        b00;
    select_ln20_3_fu_335_p3 <= 
        b11_read_reg_510 when (icmp_ln20_1_reg_553(0) = '1') else 
        b10_read_reg_515;
    select_ln20_fu_240_p3 <= 
        a10 when (icmp_ln20_fu_234_p2(0) = '1') else 
        a00;
    select_ln22_1_fu_374_p3 <= 
        grp_fu_447_p3 when (first_iter_0_fu_362_p2(0) = '1') else 
        empty_7_fu_88;
    select_ln22_2_fu_381_p3 <= 
        empty_fu_76 when (first_iter_0_fu_362_p2(0) = '1') else 
        grp_fu_447_p3;
    select_ln22_3_fu_388_p3 <= 
        grp_fu_447_p3 when (first_iter_0_fu_362_p2(0) = '1') else 
        empty_5_fu_80;
    select_ln22_fu_367_p3 <= 
        empty_6_fu_84 when (first_iter_0_fu_362_p2(0) = '1') else 
        grp_fu_447_p3;
end behav;
