#define CL_TARGET_OPENCL_VERSION 120


#include <CL/opencl.h>

#include <iostream>
#include <vector>
#include <fstream>
#include <cmath>
#include <cstdlib>
#include <string>

#define CHECK_CL(err, msg)                                         \
    do {                                                           \
        if ((err) != CL_SUCCESS) {                                 \
            std::cerr << "OpenCL error " << (err)                  \
                      << " at " << (msg) << std::endl;             \
            std::exit(EXIT_FAILURE);                               \
        }                                                          \
    } while (0)

// Default location of the bitstream generated by:
//   aoc device/saxpy.cl -o build/saxpy.aocx -board=...
#ifndef AOCX_FILE
#define AOCX_FILE "build/saxpy.aocx"
#endif

static std::vector<unsigned char> loadBinary(const std::string &file) {
    std::ifstream stream(file.c_str(), std::ios::binary | std::ios::ate);
    if (!stream.is_open()) {
        std::cerr << "Failed to open binary file: " << file << std::endl;
        std::exit(EXIT_FAILURE);
    }

    std::streamsize size = stream.tellg();
    stream.seekg(0, std::ios::beg);

    std::vector<unsigned char> buffer(static_cast<size_t>(size));
    if (!stream.read(reinterpret_cast<char *>(buffer.data()), size)) {
        std::cerr << "Failed to read binary file: " << file << std::endl;
        std::exit(EXIT_FAILURE);
    }
    return buffer;
}

int main(int argc, char **argv) {
    // Allow overriding the .aocx path on the command line, but default to AOCX_FILE.
    std::string binaryFile = AOCX_FILE;
    if (argc >= 2) {
        binaryFile = argv[1];
    }

    // Problem size
    const int N = 1 << 20;  // 1,048,576 elements
    const size_t bytes = static_cast<size_t>(N) * sizeof(float);
    const float a = 2.0f;

    std::vector<float> h_x(N);
    std::vector<float> h_y(N);
    std::vector<float> h_y_ref(N);

    for (int i = 0; i < N; ++i) {
        h_x[i] = static_cast<float>(i);
        h_y[i] = static_cast<float>(N - i);
        h_y_ref[i] = a * h_x[i] + h_y[i];  // golden reference
    }

    cl_int err;

    // 1) Platform
    cl_uint numPlatforms = 0;
    CHECK_CL(clGetPlatformIDs(0, NULL, &numPlatforms), "clGetPlatformIDs count");
    if (numPlatforms == 0) {
        std::cerr << "No OpenCL platforms found." << std::endl;
        return EXIT_FAILURE;
    }

    std::vector<cl_platform_id> platforms(numPlatforms);
    CHECK_CL(clGetPlatformIDs(numPlatforms, platforms.data(), NULL), "clGetPlatformIDs list");

    cl_platform_id chosenPlatform = NULL;
    char info[256];

    // Prefer Intel/Altera platform if present
    for (cl_uint i = 0; i < numPlatforms; ++i) {
        err = clGetPlatformInfo(platforms[i], CL_PLATFORM_VENDOR, sizeof(info), info, NULL);
        CHECK_CL(err, "clGetPlatformInfo vendor");
        std::string vendor(info);
        if (vendor.find("Intel") != std::string::npos || vendor.find("Altera") != std::string::npos) {
            chosenPlatform = platforms[i];
            break;
        }
    }
    if (!chosenPlatform) {
        chosenPlatform = platforms[0];
    }

    // 2) Device
    cl_uint numDevices = 0;
    CHECK_CL(clGetDeviceIDs(chosenPlatform, CL_DEVICE_TYPE_ALL, 0, NULL, &numDevices),
             "clGetDeviceIDs count");
    if (numDevices == 0) {
        std::cerr << "No OpenCL devices found." << std::endl;
        return EXIT_FAILURE;
    }

    std::vector<cl_device_id> devices(numDevices);
    CHECK_CL(clGetDeviceIDs(chosenPlatform, CL_DEVICE_TYPE_ALL, numDevices, devices.data(), NULL),
             "clGetDeviceIDs list");

    cl_device_id device = devices[0];

    // Print device name for your screenshot
    CHECK_CL(clGetDeviceInfo(device, CL_DEVICE_NAME, sizeof(info), info, NULL),
             "clGetDeviceInfo name");
    std::cout << "Using device: " << info << std::endl;

    // 3) Context and queue (profiling enabled)
    cl_context context = clCreateContext(NULL, 1, &device, NULL, NULL, &err);
    CHECK_CL(err, "clCreateContext");

    cl_command_queue_properties props = CL_QUEUE_PROFILING_ENABLE;
    cl_command_queue queue = clCreateCommandQueue(context, device, props, &err);
    CHECK_CL(err, "clCreateCommandQueue");

    // 4) Load .aocx binary
    std::vector<unsigned char> binary = loadBinary(binaryFile);
    const unsigned char *binaryData = binary.data();
    size_t binarySize = binary.size();
    cl_int binaryStatus = 0;

    cl_program program = clCreateProgramWithBinary(
        context,
        1,
        &device,
        &binarySize,
        &binaryData,
        &binaryStatus,
        &err);

    CHECK_CL(err, "clCreateProgramWithBinary");
    CHECK_CL(binaryStatus, "binaryStatus from clCreateProgramWithBinary");

    err = clBuildProgram(program, 1, &device, NULL, NULL, NULL);
    if (err != CL_SUCCESS) {
        size_t logSize = 0;
        clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG, 0, NULL, &logSize);
        std::vector<char> log(logSize);
        clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG, logSize, log.data(), NULL);
        std::cerr << "Build failed. Log:\n" << log.data() << std::endl;
        CHECK_CL(err, "clBuildProgram");
    }

    // 5) Kernel
    cl_kernel kernel = clCreateKernel(program, "saxpy_kernel", &err);
    CHECK_CL(err, "clCreateKernel");

    // 6) Buffers
    cl_mem d_x = clCreateBuffer(context,
                                CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR,
                                bytes,
                                h_x.data(),
                                &err);
    CHECK_CL(err, "clCreateBuffer d_x");

    cl_mem d_y = clCreateBuffer(context,
                                CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR,
                                bytes,
                                h_y.data(),
                                &err);
    CHECK_CL(err, "clCreateBuffer d_y");

    // 7) Set kernel args
    int n = N;
    CHECK_CL(clSetKernelArg(kernel, 0, sizeof(float), &a), "setArg 0 (a)");
    CHECK_CL(clSetKernelArg(kernel, 1, sizeof(cl_mem), &d_x), "setArg 1 (x)");
    CHECK_CL(clSetKernelArg(kernel, 2, sizeof(cl_mem), &d_y), "setArg 2 (y)");
    CHECK_CL(clSetKernelArg(kernel, 3, sizeof(int), &n), "setArg 3 (n)");

    // 8) Launch
    size_t globalSize[1] = { static_cast<size_t>(N) };
    cl_event kernel_event;
    CHECK_CL(clEnqueueNDRangeKernel(queue,
                                    kernel,
                                    1,
                                    NULL,
                                    globalSize,
                                    NULL,
                                    0,
                                    NULL,
                                    &kernel_event),
             "clEnqueueNDRangeKernel");

    CHECK_CL(clFinish(queue), "clFinish");

    // 9) Read back
    CHECK_CL(clEnqueueReadBuffer(queue,
                                 d_y,
                                 CL_TRUE,
                                 0,
                                 bytes,
                                 h_y.data(),
                                 0,
                                 NULL,
                                 NULL),
             "clEnqueueReadBuffer d_y");

    // 10) Verify
    bool match = true;
    const float tol = 1e-4f;

    for (int i = 0; i < N; ++i) {
        float diff = std::fabs(h_y[i] - h_y_ref[i]);
        if (diff > tol || std::isnan(h_y[i])) {
            std::cerr << "Mismatch at index " << i
                      << ": got " << h_y[i]
                      << ", expected " << h_y_ref[i]
                      << ", diff " << diff << std::endl;
            match = false;
            break;
        }
    }

    if (match) {
        std::cout << "TEST PASSED: SAXPY results are correct." << std::endl;
    } else {
        std::cout << "TEST FAILED." << std::endl;
    }

    // 11) Kernel timing
    cl_ulong start = 0, end = 0;
    CHECK_CL(clGetEventProfilingInfo(kernel_event,
                                     CL_PROFILING_COMMAND_START,
                                     sizeof(start),
                                     &start,
                                     NULL),
             "profiling START");
    CHECK_CL(clGetEventProfilingInfo(kernel_event,
                                     CL_PROFILING_COMMAND_END,
                                     sizeof(end),
                                     &end,
                                     NULL),
             "profiling END");

    double kernel_time_ms = (end - start) * 1e-6; // ns -> ms
    std::cout << "Kernel execution time: " << kernel_time_ms << " ms" << std::endl;

    // 12) Cleanup
    clReleaseMemObject(d_x);
    clReleaseMemObject(d_y);
    clReleaseKernel(kernel);
    clReleaseProgram(program);
    clReleaseCommandQueue(queue);
    clReleaseContext(context);

    return match ? EXIT_SUCCESS : EXIT_FAILURE;
}
