# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Vivado_IP_Design/Vivado_IP_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Vivado_IP_Design || ORIG_REF_NAME==Vivado_IP_Design} -quiet] -quiet

# IP: bd/Vivado_IP_Design/ip/Vivado_IP_Design_maxmul2x2_0_0/Vivado_IP_Design_maxmul2x2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Vivado_IP_Design_maxmul2x2_0_0 || ORIG_REF_NAME==Vivado_IP_Design_maxmul2x2_0_0} -quiet] -quiet

# IP: bd/Vivado_IP_Design/ip/Vivado_IP_Design_clk_wiz_0_0/Vivado_IP_Design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Vivado_IP_Design_clk_wiz_0_0 || ORIG_REF_NAME==Vivado_IP_Design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Vivado_IP_Design/ip/Vivado_IP_Design_rst_clk_wiz_0_100M_0/Vivado_IP_Design_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Vivado_IP_Design_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Vivado_IP_Design_rst_clk_wiz_0_100M_0} -quiet] -quiet

# XDC: c:/users/ankha/desktop/fpga_design/khanhtran_lab4/vivado_codes_lab4/tmp_edit_project.gen/sources_1/bd/Vivado_IP_Design/Vivado_IP_Design_ooc.xdc
