

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "5", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"],
		"CDFG" : "sobel_rgb_axis",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_axis_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "in_axis_V_data_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "in_axis_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "in_axis_V_keep_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "in_axis_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "in_axis_V_strb_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "in_axis_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "in_axis_V_user_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "in_axis_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "in_axis_V_last_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "in_axis_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "in_axis_V_id_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "in_axis_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "in_axis_V_dest_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "out_axis_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "out_axis_V_data_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "out_axis_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "out_axis_V_keep_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "out_axis_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "out_axis_V_strb_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "out_axis_V_user_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "out_axis_V_user_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "out_axis_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "out_axis_V_last_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "out_axis_V_id_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "out_axis_V_id_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "out_axis_V_dest_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "out_axis_V_dest_V", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "width", "Type" : "None", "Direction" : "I"},
			{"Name" : "height", "Type" : "None", "Direction" : "I"},
			{"Name" : "line0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_init_cols_fu_102", "Port" : "line0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "line0", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "line1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_init_cols_fu_102", "Port" : "line1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "5", "SubInstance" : "grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Port" : "line1", "Inst_start_state" : "4", "Inst_end_state" : "5"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.line0_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.line1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sobel_rgb_axis_Pipeline_init_cols_fu_102", "Parent" : "0", "Child" : ["4"],
		"CDFG" : "sobel_rgb_axis_Pipeline_init_cols",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "1026",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "width", "Type" : "None", "Direction" : "I"},
			{"Name" : "line0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "line1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "init_cols", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sobel_rgb_axis_Pipeline_init_cols_fu_102.flow_control_loop_pipe_sequential_init_U", "Parent" : "3"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112", "Parent" : "0", "Child" : ["6", "7", "8", "9"],
		"CDFG" : "sobel_rgb_axis_Pipeline_row_loop_col_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "width", "Type" : "None", "Direction" : "I"},
			{"Name" : "bound", "Type" : "None", "Direction" : "I"},
			{"Name" : "sub133", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_axis_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis",
				"BlockSignal" : [
					{"Name" : "in_axis_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "in_axis_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis"},
			{"Name" : "in_axis_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis"},
			{"Name" : "in_axis_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis"},
			{"Name" : "in_axis_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis"},
			{"Name" : "in_axis_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis"},
			{"Name" : "in_axis_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_axis"},
			{"Name" : "sub", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_axis_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis",
				"BlockSignal" : [
					{"Name" : "out_axis_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "out_axis_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis"},
			{"Name" : "out_axis_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis"},
			{"Name" : "out_axis_V_user_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis"},
			{"Name" : "out_axis_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis"},
			{"Name" : "out_axis_V_id_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis"},
			{"Name" : "out_axis_V_dest_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_axis"},
			{"Name" : "line1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "line0", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "row_loop_col_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112.mul_8ns_9ns_16_1_1_U4", "Parent" : "5"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112.mac_muladd_8ns_7ns_16ns_16_4_1_U5", "Parent" : "5"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112.mac_muladd_8ns_5ns_8ns_13_4_1_U6", "Parent" : "5"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sobel_rgb_axis_Pipeline_row_loop_col_loop_fu_112.flow_control_loop_pipe_sequential_init_U", "Parent" : "5"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_31ns_11ns_41_2_1_U30", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_axis_V_data_V_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_axis_V_keep_V_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_axis_V_strb_V_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_axis_V_user_V_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_axis_V_last_V_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_axis_V_id_V_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_axis_V_dest_V_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_axis_V_data_V_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_axis_V_keep_V_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_axis_V_strb_V_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_axis_V_user_V_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_axis_V_last_V_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_axis_V_id_V_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_axis_V_dest_V_U", "Parent" : "0"}]}
